/* Shared Gym catalogue: the active profile stores IDs and training values, never artwork. */
(function(global){
'use strict';
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function escape(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function historyKey(e){return e&&e.exerciseId?'catalog:'+e.exerciseId:String(e&&e.name||'').trim().toLowerCase();}
function create(api,catalogue){
 var list=catalogue||[],byId={},names={},dialog,view=null,returnView=null,lastFocus;
 list.forEach(e=>{byId[e.id]=e;let key=normalize(e.name);(names[key]||(names[key]=[])).push(e);});
 function preferences(){var p=api.profile();if(!p)return {favorites:[],recent:[]};if(!p.exerciseLibrary)p.exerciseLibrary={favorites:[],recent:[]};return p.exerciseLibrary;}
 function resolve(e){if(!e)return null;if(e.artworkId)return byId[e.artworkId]||null;if(e.exerciseId)return byId[e.exerciseId]||null;var matches=names[normalize(e.name)]||[];return matches.length===1?matches[0]:null;}
 function ensure(p){
  if(!p)return;var all=[];
  if(p.gymPlanner)(p.gymPlanner.plans||[]).forEach(plan=>(plan.days||[]).forEach(day=>{all=all.concat(day.exercises||[]);}));
  Object.keys(p.trainingDays||{}).forEach(d=>{all=all.concat(p.trainingDays[d].exercises||[]);});
  all.forEach(e=>{if(!e.exerciseId&&!e.artworkId){var item=resolve(e);if(item)e.exerciseId=item.id;}});
  var h=p.exerciseHistory||{};all.forEach(e=>{if(e.exerciseId){var old=h[String(e.name||'').trim().toLowerCase()];if(old&&byId[e.exerciseId]&&normalize(old.displayName)===normalize(byId[e.exerciseId].name)&&!h[historyKey(e)])h[historyKey(e)]=Object.assign({},old);}});
 }
 function history(e){var p=api.profile();return p&&p.exerciseHistory&&p.exerciseHistory[historyKey(e)];}
 function frame(n,cls){if(typeof n==='string')return '<span class="gx-art '+(cls||'')+'" aria-hidden="true" style="background-image:url('+escape(n)+');background-size:contain;background-position:center"></span>';var sheet=Math.floor((n-1)/25)+1,cell=(n-1)%25;return '<span class="gx-art '+(cls||'')+'" aria-hidden="true" style="background-image:url(assets/exercises/atlas-'+String(sheet).padStart(2,'0')+'.webp);background-position:'+cell%5*25+'% '+Math.floor(cell/5)*25+'%"></span>';}
 function thumbnail(e,index,legacy){var item=resolve(e);return '<button type="button" class="gx-thumb" data-gx="'+(item?'entry':'link')+'" data-index="'+index+'" '+(legacy?'data-legacy="true"':'')+' aria-label="'+escape(item?'Details zu '+item.name:'Bild und Variante für '+e.name+' auswählen')+'">'+(item?frame(item.frames[0]):'<span class="gx-placeholder" aria-hidden="true">＋</span>')+'</button>';}
 function preview(e,index){var item=resolve(e);if(!item)return '<button type="button" class="gx-link" data-gx="link" data-index="'+index+'">Übungsvariante und Bild zuordnen</button>';return '<button type="button" class="gx-preview" data-gx="entry" data-index="'+index+'">'+item.frames.map((n,i)=>'<span>'+frame(n)+'<small>'+(item.frames.length>1?'Phase '+(i+1):'Vorschau')+'</small></span>').join('')+'<span class="gx-preview-label">Ausführung &amp; Verlauf ›<small>Bildentwurf</small></span></button>';}
 function actionButton(action,label,extra,cls){return '<button type="button" data-gx="'+action+'" class="'+(cls||'')+'" '+(extra||'')+'>'+label+'</button>';}
 function getDialog(){
  if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='exerciseLibraryDialog';dialog.setAttribute('aria-labelledby','gxTitle');document.body.appendChild(dialog);
  dialog.addEventListener('close',()=>{view=null;returnView=null;if(lastFocus&&lastFocus.isConnected)lastFocus.focus();});dialog.addEventListener('click',click);
  dialog.addEventListener('input',ev=>{if(ev.target.id==='gxSearch'){view.query=ev.target.value;view.limit=36;renderResults();}});
  dialog.addEventListener('change',ev=>{if(ev.target.dataset.gxFilter){view[ev.target.dataset.gxFilter]=ev.target.value;view.limit=36;renderResults();}});return dialog;
 }
 function open(options){
  if(!api.profile())return;returnView=null;lastFocus=document.activeElement;view=Object.assign({screen:'browse',mode:'add',index:null,query:'',muscle:'',equipment:'',kind:'',scope:'all',layout:'list',limit:36},options||{});
  if(view.mode==='swap'||view.mode==='link'){var entry=api.entry(view.index,view.legacy);view.source=resolve(entry);view.target=entry;if(view.mode==='swap'&&view.source){view.muscle=view.source.muscle;view.kind=view.source.kind;view.scope='alternatives';}}
  view.profile=api.profile();view.date=api.date();view.context=api.context();getDialog();render();if(!dialog.open)dialog.showModal();var search=dialog.querySelector('#gxSearch');if(search)search.focus();
 }
 function validContext(){return view&&api.profile()===view.profile&&api.date()===view.date&&api.context()===view.context;}
 function selectFilter(label,key,values){return '<label>'+label+'<select data-gx-filter="'+key+'"><option value="">Alle</option>'+values.map(v=>'<option '+(view[key]===v?'selected ':'')+'value="'+escape(v)+'">'+escape(v==='strength'?'Kraft':v==='cardio'?'Cardio & Sport':v)+'</option>').join('')+'</select></label>';}
 function render(){
  var title=view.screen==='detail'?view.item.family:view.mode==='artwork'?'Bild auswählen':view.layout==='gallery'?'Galerie':view.mode==='swap'?'Übung tauschen':view.mode==='link'?'Variante zuordnen':'Übungsbibliothek';
  dialog.innerHTML='<header class="gx-header"><div><small>VOSSFIT · GYM</small><h2 id="gxTitle">'+escape(title)+'</h2></div>'+actionButton('close','✕','aria-label="Übungsbibliothek schließen"')+'</header><div id="gxBody"></div><p id="gxStatus" class="gx-status" role="status"></p>';
  if(view.screen==='detail'){renderDetail();return;}
  var muscles=Array.from(new Set(list.map(e=>e.muscle))).sort(),equipment=Array.from(new Set(list.map(e=>e.equipment))).sort();
  document.getElementById('gxBody').innerHTML='<div class="gx-menu">'+[['list','Bibliothek'],['gallery','Galerie']].map(x=>actionButton('layout',x[1],'data-value="'+x[0]+'" aria-pressed="'+(view.layout===x[0])+'"',view.layout===x[0]?'gx-active':'')).join('')+'</div>'+ (view.mode==='artwork'?'<p class="gx-muted">Wähle ein Bild für deine eigene Übung. Dein Name und deine Trainingswerte bleiben erhalten.</p>':'')+'<p class="gx-muted">'+list.length+' Varianten · nach Übungsfamilien sortiert</p>'+(view.mode==='swap'?'<p class="gx-muted">Passende Alternativen zuerst. Bei einem Wechsel werden Gewichte und abgehakte Sätze zurückgesetzt.</p>':'')+(view.mode==='link'?'<p class="gx-muted">Wähle die genaue Variante. Vorhandene Sätze und Gewichte bleiben erhalten.</p>':'')+'<label class="gx-search-label">Übung suchen<input id="gxSearch" type="search" autocomplete="off" placeholder="z. B. Bankdrücken, Brust, Kabelzug …" value="'+escape(view.query)+'"></label><div class="gx-filters">'+selectFilter('Muskelgruppe','muscle',muscles)+selectFilter('Gerät','equipment',equipment)+selectFilter('Trainingsart','kind',['strength','cardio'])+'</div><div class="gx-scopes">'+[['all','Alle'],['favorites','★ Favoriten'],['recent','Zuletzt genutzt']].concat(view.source?[['alternatives','Alternativen']]:[]).map(x=>actionButton('scope',x[1],'data-value="'+x[0]+'" aria-pressed="'+(view.scope===x[0])+'"',view.scope===x[0]?'gx-active':'')).join('')+'</div><p id="gxCount" class="gx-muted" aria-live="polite"></p><div id="gxResults"></div><footer class="gx-footer">'+(view.mode==='artwork'?'':actionButton('custom','Eigene Übung anlegen'))+actionButton('reset','Filter zurücksetzen')+'</footer>';renderResults();
 }
 function filtered(){
  var words=normalize(view.query).split(' ').filter(Boolean),favs=preferences().favorites||[],rec=preferences().recent||[],source=view.source;
  return list.filter(e=>{var hay=normalize([e.name,e.family,e.muscle,e.secondary.join(' '),e.equipment,(e.aliases||[]).join(' ')].join(' '));return (!view.muscle||e.muscle===view.muscle)&&(!view.equipment||e.equipment===view.equipment)&&(!view.kind||e.kind===view.kind)&&words.every(w=>hay.indexOf(w)!==-1)&&(view.scope!=='favorites'||favs.indexOf(e.id)!==-1)&&(view.scope!=='recent'||rec.indexOf(e.id)!==-1)&&(view.scope!=='alternatives'||!source||(e.id!==source.id&&e.kind===source.kind&&e.muscle===source.muscle));}).sort((a,b)=>{if(view.scope==='recent')return rec.indexOf(a.id)-rec.indexOf(b.id);if(view.scope==='alternatives'&&source){var sa=(a.family===source.family?10:0)+(a.equipment!==source.equipment?1:0),sb=(b.family===source.family?10:0)+(b.equipment!==source.equipment?1:0);if(sa!==sb)return sb-sa;}return a.family.localeCompare(b.family,'de')||a.name.localeCompare(b.name,'de');});
 }
 function renderResults(){
  var results=filtered(),shown=view.layout==='gallery'?results:results.slice(0,view.limit),last='',favs=preferences().favorites||[];document.getElementById('gxCount').textContent=results.length+' passende Varianten';
  var container=document.getElementById('gxResults');container.classList.toggle('gx-gallery',view.layout==='gallery');if(view.layout==='gallery'){container.innerHTML=shown.map(e=>actionButton('detail',frame(e.frames[0])+'<span>'+escape(e.name)+'</span>','data-id="'+e.id+'" title="'+escape(e.name)+'" aria-label="'+escape(e.name)+'"','gx-gallery-tile')).join('')||'<p class="gx-empty">Keine passende Übung gefunden.</p>';return;}
  document.getElementById('gxResults').innerHTML=shown.map(e=>{var heading=e.family!==last?'<h3 class="gx-family">'+escape(e.family)+'</h3>':'';last=e.family;return heading+'<article class="gx-result">'+actionButton('detail',frame(e.frames[0]),'data-id="'+e.id+'" aria-label="Details: '+escape(e.name)+'"','gx-result-image')+'<div class="gx-result-text">'+actionButton('detail',escape(e.name),'data-id="'+e.id+'"','gx-result-name')+'<small>'+escape(e.muscle)+' · '+escape(e.equipment)+'</small><div class="gx-result-actions">'+actionButton('choose',view.mode==='swap'?'Tauschen':view.mode==='link'?'Zuordnen':'Hinzufügen','data-id="'+e.id+'"','gx-primary')+actionButton('favorite',favs.indexOf(e.id)!==-1?'★':'☆','data-id="'+e.id+'" aria-label="Favorit: '+escape(e.name)+'" aria-pressed="'+(favs.indexOf(e.id)!==-1)+'"')+'</div></div></article>';}).join('')+(!shown.length?'<p class="gx-empty">Keine passende Übung gefunden. Ändere die Filter oder lege eine eigene Übung an.</p>':'')+(results.length>shown.length?actionButton('more','Weitere '+Math.min(36,results.length-shown.length)+' anzeigen','','gx-more'):'');
 }
 function sessions(item){var p=api.profile(),result=[];Object.keys(p.trainingDays||{}).sort().reverse().forEach(date=>(p.trainingDays[date].exercises||[]).forEach(e=>{if(e.exerciseId===item.id)result.push({date:date,entry:e});}));return result;}
 function renderDetail(){
  var item=view.item,logs=sessions(item),h=history({exerciseId:item.id}),fav=(preferences().favorites||[]).indexOf(item.id)!==-1;
  document.getElementById('gxBody').innerHTML=(returnView?actionButton('back','‹ Zur Auswahl','','gx-back'):'')+'<p class="gx-detail-name">'+escape(item.name)+'</p><div class="gx-detail-art" id="gxDetailArt">'+frame(item.frames[view.phase||0])+'</div><div class="gx-phases">'+item.frames.map((n,i)=>actionButton('phase',item.frames.length>1?'Phase '+(i+1):'Vorschau','data-phase="'+i+'" aria-pressed="'+((view.phase||0)===i)+'"',(view.phase||0)===i?'gx-active':'')).join('')+'</div><p class="gx-draft">Bildentwurf: Muskelmarkierungen und einzelne Bewegungsphasen sind noch nicht abschließend geprüft.</p><div class="gx-detail-tags"><span>'+escape(item.muscle)+'</span><span>'+escape(item.equipment)+'</span></div>'+(item.secondary.length?'<p class="gx-muted">Unterstützend: '+escape(item.secondary.join(', '))+'</p>':'')+'<h3>Ausführung</h3><ol class="gx-tips">'+item.tips.map(t=>'<li>'+escape(t)+'</li>').join('')+'</ol><h3>Dein Verlauf</h3>'+(h?'<p class="gx-muted">Zuletzt: '+h.lastSets+' × '+h.lastReps+' · '+h.lastWeight+' kg</p>':'')+(logs.length?'<div class="gx-history">'+logs.slice(0,10).map(log=>{var e=log.entry;return '<div><time>'+escape(log.date.split('-').reverse().join('.'))+'</time><span>'+(item.kind==='cardio'?escape(e.durationMin||0)+' Min. · '+escape(e.distanceKm||0)+' km':e.rows?e.rows.filter(r=>r.done).length+'/'+e.rows.length+' Sätze · '+e.rows.map(r=>escape(r.weight)+' kg × '+escape(r.reps)).join(' / '):escape(e.sets||0)+' × '+escape(e.reps||0)+' · '+escape(e.weight||0)+' kg')+'</span></div>';}).join('')+'</div>':'<p class="gx-muted">Noch kein Training mit dieser Variante gespeichert.</p>')+'<footer class="gx-footer">'+actionButton('choose',view.mode==='artwork'?'Dieses Bild auswählen':view.mode==='swap'?'Diese Übung tauschen':view.mode==='link'?'Diese Variante zuordnen':'Zum Training hinzufügen','data-id="'+item.id+'"','gx-primary')+actionButton('favorite',fav?'★ Favorit':'☆ Favorit','data-id="'+item.id+'" aria-pressed="'+fav+'"')+(view.entryIndex!=null?actionButton('alternatives','Alternative auswählen'):'')+'</footer>';
 }
 function choose(id){if(!validContext()){document.getElementById('gxStatus').textContent='Das Profil oder der Trainingstag hat sich geändert. Bitte öffne die Auswahl erneut.';return;}var item=byId[id];if(!item)return;if(view.mode==='artwork'){var callback=view.onArtwork;dialog.close();if(callback)callback(item);return;}if(api.select(item,view)===false){document.getElementById('gxStatus').textContent='Setze das abgeschlossene Training zum Bearbeiten zuerst fort.';return;}var prefs=preferences();prefs.recent=[id].concat((prefs.recent||[]).filter(x=>x!==id)).slice(0,30);api.save();dialog.close();}
 function click(ev){
  var b=ev.target.closest('[data-gx]');if(!b)return;var action=b.dataset.gx,id=b.dataset.id;
  if(action==='close'){dialog.close();return;}if(action==='choose'){choose(id);return;}
  if(action==='favorite'){if(!validContext())return;var p=preferences(),f=p.favorites||[];p.favorites=f.indexOf(id)!==-1?f.filter(x=>x!==id):f.concat(id);api.save();if(view.screen==='detail')renderDetail();else renderResults();return;}
  if(action==='detail'){returnView=Object.assign({},view);view.screen='detail';view.item=byId[id];view.phase=0;render();dialog.scrollTop=0;return;}
  if(action==='back'){view=returnView;returnView=null;render();return;}
  if(action==='phase'){view.phase=Number(b.dataset.phase);document.getElementById('gxDetailArt').innerHTML=frame(view.item.frames[view.phase]);dialog.querySelectorAll('[data-gx="phase"]').forEach(x=>{var selected=Number(x.dataset.phase)===view.phase;x.classList.toggle('gx-active',selected);x.setAttribute('aria-pressed',String(selected));});return;}
  if(action==='layout'){view.layout=b.dataset.value;render();return;}
  if(action==='scope'){view.scope=b.dataset.value;view.limit=36;render();return;}
  if(action==='more'){view.limit+=36;renderResults();return;}
  if(action==='reset'){view.query='';view.muscle='';view.equipment='';view.kind='';view.scope='all';view.limit=36;render();return;}
  if(action==='custom'){var options=Object.assign({},view);if(!validContext())return;dialog.close();api.custom(options);return;}
  if(action==='alternatives'){var options={mode:'swap',index:view.entryIndex,legacy:view.legacy};open(options);}
 }
 function openEntry(index,legacy){var e=api.entry(index,legacy),item=resolve(e);if(!item){open({mode:'link',index:index,legacy:legacy});return;}open({screen:'detail',item:item,phase:0,entryIndex:index,legacy:legacy});}
 document.addEventListener('click',ev=>{var b=ev.target.closest('[data-gx]');if(!b||b.closest('#exerciseLibraryDialog'))return;var i=Number(b.dataset.index),legacy=b.dataset.legacy==='true';if(b.dataset.gx==='library')open();if(b.dataset.gx==='gallery')open({layout:'gallery'});if(b.dataset.gx==='entry'){ev.stopPropagation();openEntry(i,legacy);}if(b.dataset.gx==='link'){ev.stopPropagation();open({mode:'link',index:i,legacy:legacy});}},true);
 return {open:open,resolve:resolve,ensure:ensure,history:history,historyKey:historyKey,thumbnail:thumbnail,preview:preview,byId:byId,frame:frame,openEntry:openEntry};
}
global.VossFitExercises={create:create,normalize:normalize,historyKey:historyKey};
if(typeof module!=='undefined')module.exports=global.VossFitExercises;
})(typeof window!=='undefined'?window:globalThis);
